i3display: silenced which call and added error message if xrandr is not found

diff --git a/scripts/i3display b/scripts/i3display
--- a/scripts/i3display
+++ b/scripts/i3display
@@ -3,7 +3,8 @@
 DISPLAY_BUILTIN=LVDS1
 DISPLAY_EXTERNAL=HDMI1
 
-if ! which xrandr; then
+if ! which xrandr &>/dev/null; then
+	echo "Error: xrandr not found" >&2
 	exit 1
 fi
 
